import { Link } from 'react-router-dom';
import { Footer } from '@/components/Footer/Footer';
import { MissionCard } from '@/components/MissionCard/MissionCard';
import { Navbar } from '@/components/Navbar/Navbar';
import { useHome } from '@/hooks/useHome';

export function PortailPage() {
  const { data: home, isLoading, isError } = useHome();
  return <><Navbar /><main id="contenu"><section className="hero"><div className="container"><div className="row align-items-center g-4"><div className="col-lg-7"><p className="eyebrow hero-eyebrow">Secteur associatif · humanitaire · philanthropique</p><h1>L'engagement qui a du sens, réuni au même endroit</h1><p className="hero-lead">ONG, associations, fondations et Waqfs rencontrent les candidats à l'engagement et le mécénat de compétences.</p><div className="d-flex flex-column flex-sm-row gap-2"><Link to="/missions" className="btn btn-accent btn-lg">Voir les missions</Link><Link to="/mecenat" className="btn btn-outline-light btn-lg">Proposer un mécénat</Link></div></div><div className="col-lg-5"><div className="hero-stats card"><div className="hero-stat"><span className="hero-stat-value">{home?.stats.open_offers ?? '—'}</span><span className="hero-stat-label">missions ouvertes</span></div><div className="hero-stat"><span className="hero-stat-value">{home?.stats.verified_organizations ?? '—'}</span><span className="hero-stat-label">organisations vérifiées</span></div><div className="hero-stat"><span className="hero-stat-value">{home?.stats.candidate_price ?? '100 %'}</span><span className="hero-stat-label">gratuit pour les candidats</span></div></div></div></div></div></section>
    <section className="app-section"><div className="container"><div className="section-head d-flex flex-wrap justify-content-between align-items-end gap-2"><div><p className="eyebrow">À la une</p><h2>Missions proposées sur la plateforme</h2><p>Les dernières missions publiées par les organisations.</p></div><Link to="/missions" className="btn btn-primary">Voir toutes les missions</Link></div>{isLoading && <p>Chargement des missions…</p>}{isError && <div className="alert alert-danger">Impossible de charger les données de la plateforme.</div>}{home && <div className="row g-3">{home.featured_offers.map((mission) => <div className="col-md-6 col-lg-3" key={mission.id}><MissionCard mission={mission} /></div>)}</div>}</div></section>
    {home?.sponsor && <section className="app-section"><div className="container"><div className="ad-slot"><span className="ad-tag">{home.sponsor.label || 'Partenariat'}</span><p className="mb-0 mt-1">{home.sponsor.copy}</p>{home.sponsor.target_url && <a href={home.sponsor.target_url} target="_blank" rel="noreferrer">Découvrir le partenaire</a>}</div></div></section>}</main><Footer /></>;
}